dev/bases/veidemann/contentwriter_volume_patch.yaml, dev/bases/veidemann/kustomization.yaml, dev/bases/veidemann/persistence/backup-pvc.yaml, dev/bases/veidemann/persistence/delivery-pvc.yaml, dev/bases/veidemann/persistence/invalidwarcs-pvc.yaml, dev/bases/veidemann/persistence/kustomization.yaml, dev/bases/veidemann/persistence/validwarcs-pvc.yaml, dev/bases/veidemann/persistence/warcs-pvc.yaml
- created warc PVC's
- claim veidemann-warcs in contentwriter
=> Persistence in dev

bases/veidemann-warcvalidator/deployment.yaml, bases/veidemann-warcvalidator/kustomization.yaml, dev/bases/veidemann/kustomization.yaml, dev/bases/veidemann/warcvalidator_env_patch.yaml, dev/bases/veidemann/warcvalidator_volume_patch.yaml
requires merge of PR: https://github.com/nlnwa/veidemann-deploy/pull/7
=> veidemann-warcvalidator

bases/pywb/README.md, bases/pywb/config.yaml, bases/pywb/default.conf, bases/pywb/deployment.yaml, bases/pywb/kustomization.yaml, bases/pywb/service.yaml, dev/bases/pywb/config.yaml, dev/bases/pywb/default.conf, dev/bases/pywb/deployment_volume_patch.yaml, dev/bases/pywb/ingressroute.yaml, dev/bases/pywb/kustomization.yaml
=> Pywb kustomization

bases/veidemann-controller/deployment.yaml, bases/veidemann-frontier/deployment.yaml, bases/veidemann-harvester/deployment.yaml
Updates image versions of components depending of webarchive-commons which contain the actual fix for IPv4 parsing.
=> Fix IPv4 parsing

bases/veidemann-controller/deployment.yaml, bases/veidemann-controller/envoy.yaml
Envoy API v3. Configuration syntax changes.
=> Update veidemann-controller envoy container to version 1.15.2

bases/veidemann-controller/deployment.yaml, bases/veidemann-controller/envoy.yaml
Update envoy configuration to be api v3 compliant.
=> Update envoy proxy to v1.16.0

bases/kube-prometheus/vendor/kustomization.yaml, bases/kube-prometheus/vendor/manifests/alertmanager-secret.yaml, bases/kube-prometheus/vendor/manifests/grafana-dashboardDefinitions.yaml, bases/kube-prometheus/vendor/manifests/grafana-service.yaml, bases/kube-prometheus/vendor/manifests/kube-state-metrics-clusterRole.yaml, bases/kube-prometheus/vendor/manifests/kube-state-metrics-clusterRoleBinding.yaml, bases/kube-prometheus/vendor/manifests/kube-state-metrics-deployment.yaml, bases/kube-prometheus/vendor/manifests/kube-state-metrics-service.yaml, bases/kube-prometheus/vendor/manifests/kube-state-metrics-serviceAccount.yaml, bases/kube-prometheus/vendor/manifests/node-exporter-daemonset.yaml, bases/kube-prometheus/vendor/manifests/prometheus-adapter-deployment.yaml, bases/kube-prometheus/vendor/manifests/prometheus-operator-serviceMonitor.yaml, bases/kube-prometheus/vendor/manifests/prometheus-prometheus.yaml, bases/kube-prometheus/vendor/manifests/prometheus-rules.yaml, bases/kube-prometheus/vendor/manifests/setup/prometheus-operator-0alertmanagerConfigCustomResourceDefinition.yaml, bases/kube-prometheus/vendor/manifests/setup/prometheus-operator-0alertmanagerCustomResourceDefinition.yaml, bases/kube-prometheus/vendor/manifests/setup/prometheus-operator-0podmonitorCustomResourceDefinition.yaml, bases/kube-prometheus/vendor/manifests/setup/prometheus-operator-0prometheusCustomResourceDefinition.yaml, bases/kube-prometheus/vendor/manifests/setup/prometheus-operator-0servicemonitorCustomResourceDefinition.yaml, bases/kube-prometheus/vendor/manifests/setup/prometheus-operator-0thanosrulerCustomResourceDefinition.yaml, bases/kube-prometheus/vendor/manifests/setup/prometheus-operator-clusterRole.yaml, bases/kube-prometheus/vendor/manifests/setup/prometheus-operator-clusterRoleBinding.yaml, bases/kube-prometheus/vendor/manifests/setup/prometheus-operator-deployment.yaml, bases/kube-prometheus/vendor/manifests/setup/prometheus-operator-service.yaml, bases/kube-prometheus/vendor/manifests/setup/prometheus-operator-serviceAccount.yaml
This fixes most importantly repair of WAL replay by removal of livenessProbe
on the prometheus container.
=> kube-prometheus: Update vendoring

bases/veidemann-controller/deployment.yaml, bases/veidemann-db-initializer/job.yaml, bases/veidemann-frontier/deployment.yaml
=> Fix regression in rethinkdb-adapter

bases/veidemann-controller/deployment.yaml
Fixes the issue where the controller was unresponsive when starting jobs.
=> Upgrade veidemann-controller to version 0.6.6

bases/veidemann-controller/deployment.yaml
Disallow scheduler to start already running jobs.
=> Update veidemann-controller to version 0.6.7

bases/veidemann-harvester/deployment.yaml
- Database query retries
- Better tracing
- Improved script caching
=> Update veidemann-browser-controller to version v0.1.5

bases/veidemann-controller/deployment.yaml
Only aggregate running job executions if requesting specific id's.
=> Update veidemann controller to version 0.6.8

bases/veidemann-harvester/deployment.yaml
Fixes batch write of crawl logs.
=> Update veidemann-harvester to v0.1.6

bases/veidemann-dashboard/deployment.yaml
=> Update veidemann-dashboard to version v0.15.3

bases/veidemann-controller/deployment.yaml
No aggregation of jobexecution status.
=> Update veidemann-controller to version 0.6.9

bases/veidemann-dashboard/deployment.yaml
=> Update veidemann-dashboard to version v0.16.0

bases/veidemann-dns-resolver/deployment.yaml, dev/bases/veidemann/Corefile, dev/bases/veidemann/dnsresolver_volume_patch.yaml, dev/bases/veidemann/kustomization.yaml
=> Update veidemann-dns-resolver to version v0.2.8

bases/veidemann-dashboard/deployment.yaml
Add column to show desired state for crawlexecution/jobexecution.
=> Update veidemann-dashboard to version v0.18.2

bases/veidemann-controller/deployment.yaml, bases/veidemann-dashboard/deployment.yaml, bases/veidemann-dns-resolver/deployment.yaml
Add controller/dashboard support for queries on implicit database fields.
=> Fix invalid WARC header field WARC-IP-Address

bases/veidemann-frontier/deployment.yaml
Fixes selection of next crawl execution.
=> Fixes in veidemann-frontier

bases/veidemann-dashboard/deployment.yaml
- Fix keyboard-shortcuts
- Switch to echarts
=> Update veidemann-dashboard to version 0.18.8
